### ISSUE TITLE
will it support JP client

### ISSUE THREAD

**Issue by jacky50403** [ahjsrhj/AlexanderHelper#1]
After I add to overlay plugin
It's entire nothing

**Comment by ahjsrhj** [comment]
I try to add the custom boss name entry, just add it on url query like this 
`https://ahjsrhj.github.io/AlexanderHelper/?p1Main=有生命活水&p1Sub=活水之手&p2Main=残暴正义号&p2Sub=巡洋驱逐舰`
Just change `有生命活水` `活水之手` to JP client boss name. 
It's not have to enough test so I can't promise it can work.
